trigger:
  - main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an image that suits your needs

steps:
  - script: |
      # Add commands to deploy your website here
      # For example, copy your HTML/CSS files to a server using SCP, FTP, or another method
    displayName: 'Deploy Static Website'

