trigger:
  - main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use an image that suits your needs

steps:
  - script: |
      sudo apt update
      sudo apt install apache2
      cp . /var/www/html
      sudo systemctl restart apache2
    displayName: 'Deploy Static Website'
  
  

